apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-container
        image: 593318841689.dkr.ecr.us-east-1.amazonaws.com/my-cloud-monitoring:1.0
        ports:
        - containerPort: 5000
